import { StyleSheet } from 'react-native';
import { colors } from '../../../styles/colors';
import { mvs } from '../../../config/metrices';

export const styles = StyleSheet.create({
  map: {
    flex: 1,
    width: '100%',
  },
  // Small loading overlay instead of full screen
  loadingOverlay: {
    position: 'absolute',
    top: 16,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    gap: 8,
  },
  loadingOverlayText: {
    fontSize: 13,
    color: colors.text,
    fontWeight: '500',
  },
  // Marker Styles
  markerTouchable: {
    padding: 4,
  },
  markerContainer: {
    alignItems: 'center',
  },
  markerPin: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#7625D7',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 6,
  },
  markerPinSelected: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 4,
    backgroundColor: '#5E1DB3',
  },
  markerTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#7625D7',
    marginTop: -2,
  },
  markerTriangleSelected: {
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderTopWidth: 14,
    borderTopColor: '#5E1DB3',
  },
  // Clinic Card Styles
  clinicCard: {
    position: 'absolute',
    backgroundColor: 'white',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  cardContent: {
    padding: 10,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: 120,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
  },
  clinicImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
    backgroundColor: colors.lightGray,
  },
  featuredBadgeOnImage: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  featuredTextOnImage: {
    fontSize: 11,
    fontWeight: '600',
    color: '#333',
  },
  clinicInfo: {
    paddingHorizontal: 2,
  },
  typeRatingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  businessTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  businessTypeChip: {
    backgroundColor: '#F0E6FA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  businessTypeText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.primary,
  },
  clinicName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginTop: 2,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  ratingText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  cardPointer: {
    position: 'absolute',
    bottom: -10,
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderTopWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'white',
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    paddingBottom: mvs(20),
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 8,
  },
  locationInfo: {
    paddingHorizontal: mvs(15),
    paddingTop: mvs(12),
    paddingBottom: mvs(10),
    flexDirection: 'row',
    alignItems: 'center',
    gap: mvs(10),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  locationInfoTextContainer: {
    flex: 1,
  },
  locationInfoText: {
    fontSize: 14,
    color: colors.black,
    fontWeight: '500',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: mvs(15),
    paddingTop: mvs(15),
    gap: mvs(12),
  },
  doneButton: {
    flex: 1,
    backgroundColor: colors.lightGray || '#F5F5F5',
    paddingVertical: mvs(14),
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  doneButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  currentLocationButton: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: mvs(14),
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  currentLocationButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  // Search Bar Styles
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mvs(15),
    paddingVertical: mvs(10),
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchContainer: {
    flex: 1,
    backgroundColor: colors.gray,
    borderRadius: 12,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mvs(15),
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
    marginLeft: mvs(10),
  },
  searchIcon: {
    marginLeft: 0,
  },
  clearButton: {
    marginLeft: mvs(10),
    padding: mvs(5),
  },
  // Search Results Modal Styles
  searchModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  searchResultsContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    paddingBottom: mvs(20),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  searchResultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: mvs(20),
    paddingVertical: mvs(15),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mvs(20),
    paddingVertical: mvs(15),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultIcon: {
    marginRight: mvs(15),
  },
  searchResultText: {
    flex: 1,
  },
  searchResultMainText: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
    marginBottom: mvs(4),
  },
  searchResultSecondaryText: {
    fontSize: 14,
    color: colors.secondaryText,
  },
  searchLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: mvs(20),
    gap: mvs(10),
  },
  searchLoadingText: {
    fontSize: 14,
    color: colors.secondaryText,
  },
  // Clinic search result styles
  clinicResultIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: mvs(12),
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: mvs(20),
    paddingVertical: mvs(10),
    backgroundColor: '#F5F5F5',
    gap: mvs(8),
  },
  sectionHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  noResultsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: mvs(30),
  },
  noResultsText: {
    fontSize: 14,
    color: colors.secondaryText,
  },
});
 