import { colors } from '../../../styles/colors';
import {
    StyleSheet,
  } from 'react-native';
export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    doctorHeaderContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.white,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    doctorHeaderCenter: {
      flex: 1,
      alignItems: 'center',
    },
    doctorName: {
      fontSize: 17,
      fontWeight: '600',
      color: colors.text,
    },
    consultationTime: {
      fontSize: 13,
      color: colors.secondaryText,
      marginTop: 2,
    },
    endButton: {
      backgroundColor: '#ef4444',
      paddingHorizontal: 16,
      paddingVertical: 6,
      borderRadius: 6,
    },
    endButtonText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '600',
    },
    placeholder: {
      width: 60,
    },
    clinicInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderBottomWidth: 1,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      borderBottomColor: colors.border,
    },
    clinicLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    clinicImage: {
      width: 48,
      height: 48,
      backgroundColor: '#e5e7eb',
      borderRadius: 8,
      marginRight: 12,
    },
    clinicName: {
      fontSize: 15,
      fontWeight: '600',
      color: '#111827',
    },
    clinicLocation: {
      fontSize: 11,
      color: '#6b7280',
      marginTop: 2,
    },
    consultButton: {
      backgroundColor: colors.black,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 4,
    },
    consultButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '600',
    },
    visitButton: {
      backgroundColor: colors.lightGray,
      paddingHorizontal: 20,
      paddingVertical: 8,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    visitButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    messagesContainer: {
      flex: 1,
      backgroundColor: '#fff',
    },
    messagesContent: {
      padding: 16,
    },
    messageContainer: {
      marginBottom: 16,
    },
    botMessageWithAvatar: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    avatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      marginRight: 8,
    },
    botMessageContent: {
      flex: 1,
    },
    messageHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      gap: 8,
    },
    senderName: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    timestamp: {
      fontSize: 12,
      color: colors.secondaryText,
    },
    userMessageWrapper: {
      alignItems: 'flex-end',
    },
    userMessageHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      gap: 8,
    },
    userMessageRow: {
      flexDirection: 'row-reverse',
      alignItems: 'flex-start',
    },
    userMessage: {
      maxWidth: '80%',
    },
    userMessageText: {
      fontSize: 15,
      color: colors.text,
      backgroundColor: colors.lightGray,
      padding: 12,
      borderRadius: 10,
    },
    imagesRow: {
      flexDirection: 'row',
      marginTop: 8,
      gap: 8,
      justifyContent: 'flex-end',
    },
    uploadedImage: {
      width: 80,
      height: 80,
      borderRadius: 8,
    },
    botMessageWrapper: {
      alignItems: 'flex-start',
    },
    botMessage: {
      maxWidth: '85%',
    },
    botMessageText: {
      backgroundColor: colors.primary,
      borderRadius: 10,
      padding: 12,
      fontSize: 15,
      color: '#fff',
      lineHeight: 20,
    },
    suggestionsContainer: {
      marginTop: 12,
      gap: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    suggestionCard: {
      width: '48%',
      minHeight: 70,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.lightGray,
      padding: 12,
      borderRadius: 8,
    },
    suggestionIcon: {
      width: 40,
      height: 40,
      borderRadius: 8,
      overflow: 'hidden',
      marginRight: 12,
    },
    suggestionImage: {
      width: 40,
      height: 40,
    },
    suggestionContent: {
      flex: 1,
    },
    suggestionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    suggestionSubtitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    suggestionSubtitle: {
      fontSize: 10,
      color: colors.secondaryText,
      flex: 1,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: '#f0f0f0',
      gap: 5,
    },
    cameraButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.gray,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    input: {
      flex: 1,
      backgroundColor: '#f3f4f6',
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      fontSize: 15,
      marginRight: 8,
      borderColor: colors.border,
      borderWidth: 1,
    },
    sendButton: {
      width: 44,
      height: 44,
      backgroundColor: '#7c3aed',
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
  